[SeaFloor]
sandTilingX = 1.0
sandTilingY = 1.0
sandRoughness = 0.89

; UE-style caustics (causticSpeed: 1.0 = normal, 0.5 = half, 2.0 = double)
causticGlobalSize = 3.0
causticSpeed = 0.2
waterColorR = 0.31
waterColorG = 0.81
waterColorB = 0.53
normalStrength = 0.05
causticStrength = 1.2

maskRadius = 0.45
maskSoftness = 0.1
