[Decals]
; Default cammo decals settings
; Colors are sRGB 0.0-1.0

; minColor is mapped to texture black/transparent parts (if any)
minColorR = 0.8
minColorG = 0.8
minColorB = 0.8

; maxColor is mapped to texture white/opaque parts
maxColorR = 1.0
maxColorG = 1.0
maxColorB = 1.0

roughness = 0.15

; Texture located in Resources/Textures/P_426/
texture = Textures/P_426/T_D_Decals.ktx
