; Livery kombinacije za P-426
; useTexture: 0 = solid baseColor, 1 = tekstura (grayscale remap)
; Boje su sRGB 0.0-1.0 (hex / 255)

[Settings]
defaultLivery = 3

[Livery1]
name         = MILITECH
useTexture   = 0
primaryR     = 0.024
primaryG     = 0.322
primaryB     = 0.000
secondaryR   = 0.345
secondaryG   = 0.482
secondaryB   = 0.192

[Livery2]
name         = EXPO
useTexture   = 0
primaryR     = 0.302
primaryG     = 0.110
primaryB     = 0.443
secondaryR   = 0.984
secondaryG   = 0.192
secondaryB   = 0.522

[Livery3]
name         = ON BRAND
useTexture   = 0
primaryR     = 0.533
primaryG     = 0.051
primaryB     = 0.114
secondaryR   = 0.153
secondaryG   = 0.141
secondaryB   = 0.114

[Livery4]
name         = GOLDEN
useTexture   = 0
primaryR     = 0.624
primaryG     = 0.427
primaryB     = 0.035
secondaryR   = 0.000
secondaryG   = 0.016
secondaryB   = 0.690

[Livery5]
name              = DEEP PATROL
useTexture        = 1
texture           = LiveryOne.ktx
uvScale           = 1.0
minBrightnessR    = 0.01
minBrightnessG    = 0.01
minBrightnessB    = 0.01
maxBrightnessR    = 0.05
maxBrightnessG    = 0.05
maxBrightnessB    = 0.05
secondaryR        = 0.620
secondaryG        = 0.216
secondaryB        = 0.004

[Livery6]
name              = CAMMO
useTexture        = 1
texture           = LiveryTwo.ktx
uvScale           = 0.5
minBrightnessR    = 0.08
minBrightnessG    = 0.08
minBrightnessB    = 0.08
maxBrightnessR    = 0.55
maxBrightnessG    = 0.55
maxBrightnessB    = 0.55
secondaryR        = 0.745
secondaryG        = 1.000
secondaryB        = 0.357
