[MetalPaintedA1]
; Osnovna boja (tamno siva/crna)
baseColorR = 0.29
baseColorG = 0.29   
baseColorB = 0.29

; Raspon hrapavosti (roughness) koji se miješa preko teksture
roughnessMin = 0.35
roughnessMax = 0.75
metallic = 1.0
reflectance = 0.9
uvScaleRoughness = 1.0
