[MetalPaintedB2]
; Osnovna boja (nešto svjetlija ili drugačija siva)
baseColorR = 0.10
baseColorG = 0.10
baseColorB = 0.10

; Raspon hrapavosti (roughness) koji se miješa preko teksture
roughnessMin = 0.35
roughnessMax = 0.65
metallic = 1.0
reflectance = 0.05
uvScaleRoughness = 1.0
