[PanelGap]
; Boja procijepa (obično crna) i alpha (0.0 = potpuno prozirno, 1.0 = crna traka)
baseColorR = 0.0
baseColorG = 0.0
baseColorB = 0.0
alpha = 0.4

; PBR
roughness = 0.3
metallic = 0.0

; Normala
normalMap = Textures/P_426/T_N_PGAP_A.ktx
normalIntensity = 2.0
uvScale = 1.0
