[Water]
windDirX = 0.8
windDirY = 0.6
waveSpeed = 0.45
uvScale = 1.2
foamScale = 2.0
; Tahiti crystal clear lagoon

shallowColorR = 0.00
shallowColorG = 0.10   
shallowColorB = 0.16

deepColorR = 0.0
deepColorG = 0.05
deepColorB = 0.08

baseOpacity = 0.78
normalStrength = 1.1
foamAmount = 1.2
roughness = 0.08
fresnelPower = 5.0
reflectance = 0.78